### ISSUE TITLE
NodeMCU (ESP8266) compiling error

### ISSUE THREAD

**Issue by Rtully** [bmellink/IBusBM#6]
Hi, even though nodeMCU is mentioned in the documentation I am getting this compile error from the IBusBM library. Simply trying to load one of the examples to read ibus servo signals.

.../src/IBusBM.cpp:114:10: error: #error "Only support for AVR, ESP32 and STM32 architectures."
         #error "Only support for AVR, ESP32 and STM32 architectures."
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

Thanks

**Comment by bmellink** [comment]
The NodeMCU 1.0 is an architecture based on the ESP8266 chip which is different from the ESP32  architecture. See https://makeradvisor.com/esp32-vs-esp8266/  and here: https://elekonika.com/esp32-vs-esp8266/ 
The ESP32 is newer and I tried implementing the library for the ESP8266 but ran into issues with the timer and then dropped the project. Another user added support for the STM32 later on.
The documentation specifies NodeMCU, because the NodeMCU-32S board is supported as it is based on the ESP32 chip. Maybe I should clarify this.
